[package]
name = "set5"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
sha256 = "*"
openssl = "*"
color-eyre = "0.5"
num-bigint = {version = "*", features = ["rand"]}
sha1 = "*"
